env:
  - DJANGO=3.0
  - DJANGO=3.1.7
language: python
python:
  - "3.7"
  - "3.8"
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
before_install:
  - sudo apt-get update
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 12
  - sleep 1
install:
  - pip install django==${DJANGO} Pillow psycopg2-binary
  - pip install .
before_script:
  - psql -c 'create database test_jsonate;' -U postgres
  - psql test_jsonate -c 'CREATE EXTENSION IF NOT EXISTS hstore;' -U postgres
script: python test_project/manage.py test test_app
