# Generated by Django 5.0.6 on 2024-05-15 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_alter_mymodel_null_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='datetime_field',
            field=models.DateTimeField(default=datetime.datetime(2011, 1, 11, 11, 11, 11, tzinfo=datetime.timezone.utc)),
        ),
    ]
